services:

  api:
    image: ghcr.io/battmoteam/battmoapp_api:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: api
    restart: always
    ports:
      - "8081:8081"
      - "8080:8080"

    command: julia --project=. -e 'include("api.jl")' --color=yes --depwarn=no --project=@. --sysimage="pre-compilation/sysimage.so" -q -i -- $$(dirname $$0)/../bootstrap.jl -s=true "$$@"