name: Publish and Deploy

on:
  push:
    branches:
      - main

env:
  SSH_USER: lhendrix
  SSH_HOST: 51.68.188.78
  REGISTRY: ghcr.io
  IMAGE_NAME: battmoteam/battmoapp:latest
  WORKDIR: battmogui

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u lorenah84 --password-stdin

      - name: Build
        run: |
          docker compose -f docker-compose-deploy.yml build

      - name: Publish
        run: docker compose -f docker-compose-deploy.yml push
